User auth
wolox-training/jp-rails pull request #3
Opened 2022-01-24 19:30 UTC by jdperez13

## Summary
Adding the user auth for loggin

## Trello card
https://trello.com/c/gOA97NhI/23-crear-modelo-de-user-implementar-autenticaci%C3%B3n

2022-01-24 19:37 UTC, ranuccimariano requested changes

2022-01-24 19:37 UTC, ranuccimariano commented on app/models/user.rb
> +  end
missing empty line at the end of file

2022-01-24 20:23 UTC, jdperez13 commented on app/models/user.rb
> +  end
done!

2022-01-25 13:25 UTC, ranuccimariano approved these changes

2022-01-26 21:52 UTC, merged